#!/bin/bash
if [ $# -eq 0 ]; then
  # No arguments, run with default (Android, IOS with Compose UI) plus tests
  ./gradlew :composeApp:run --args="--include-tests"
else
  # Pass all provided arguments
  ./gradlew :composeApp:run --args="$*"
fi